// All visible copy, EN and ES. Templates read copy[lang].
// Rules: no em or en dashes, no invented facts, Relaxed Precision voice.

const en = {
  langName: "English",
  otherLangLabel: "Español",
  skip: "Skip to content",
  nav: {
    products: "Products",
    professionals: "For Professionals",
    about: "About",
    contact: "Contact",
    cta: "Request pricing",
    menu: "Menu",
    close: "Close",
    home: "Fabeaulous Feet home",
  },
  cta: {
    pricing: "Request pricing",
    whatsapp: "Message us on WhatsApp",
    email: "Email us",
    system: "See the system",
    distributor: "Become a distributor",
    waText: "Hi Fabeaulous Feet, I'd like professional pricing for the pedicure system.",
  },
  footer: {
    blurb: "A professional pedicure system designed by people who do pedicures. File, steel tip and fresh discs for every client.",
    explore: "Explore",
    talk: "Talk to us",
    follow: "Follow",
    pros: "Professional use only. Sold to trained nail and foot care professionals.",
    rights: "All rights reserved.",
    langSwitch: "Ver en español",
  },

  home: {
    title: "Fabeaulous Feet | Professional Pedicure System",
    description: "Electric pedicure file, medical grade stainless steel tip and disposable REMOVE and POLISH discs. Built for nail and foot care professionals in Mexico, Canada and the US.",
    hero: {
      label: "Professional Pedicure System",
      line1: "Smooth feet.",
      line2: "Easy hands.",
      sub: "An electric file, a stainless steel tip and a fresh pair of discs for every client. Built by pedicure professionals for pedicure professionals.",
      imgAlt: "Technician using a Fabeaulous Feet electric file on a client's foot under the LED MagniVac Lamp",
      note: "Designed in Canada. Shipped from Mexico.",
    },
    manifesto: {
      label: "Why it exists",
      small: "Blades and scrapers still do most callus work.",
      big: "Blades cut clients. The same motion, season after season, wears out your wrists. We built a system that does the work so your hands don't have to.",
      injuries: "Tendinitis. Bursitis. Epicondylitis. Carpal tunnel.",
      injuriesNote: "The repetitive strain injuries this system was designed to prevent.",
    },
    steps: {
      label: "How it works",
      title: "Two discs. One gentle glide.",
      intro: "The whole callus routine fits in four moves. Use no pressure. Let the speed do the work.",
      items: [
        { n: "01", title: "Peel on a fresh disc", body: "Self-adhesive discs stick straight onto the stainless steel tip. A new set for every client, so there is nothing to sterilize between services." },
        { n: "02", title: "REMOVE the hard skin", body: "The blue REMOVE disc handles heavy callus, corns and dry, peeling skin. Use it only where it is needed and keep clear of sensitive areas." },
        { n: "03", title: "POLISH the whole foot", body: "The gray POLISH disc smooths every surface of the foot. Some clients only need this step." },
        { n: "04", title: "Peel off. Discard. Done.", body: "Both discs go in the bin. The client leaves with soft feet and you move on to the next service with the same steady hands." },
      ],
    },
    tip: {
      label: "The tip",
      title: "Flat where others are round.",
      body: "Most bits are barrel shaped and touch a thin strip of skin, which makes heat and burns more likely. Our medical grade stainless steel tip is flat and rounded, so it covers more surface and shows you exactly how far you've gone.",
      points: [
        "Sized to work around and between the toes",
        "File eases to low speed if you press too hard",
        "You stay in control of how much you remove",
      ],
      imgAlt: "Close-up of the Fabeaulous Feet electric file with a disc on the stainless steel tip, working on a client's heel",
    },
    system: {
      label: "The system",
      title: "Everything the station needs.",
      intro: "Start with the complete file system, then add discs, tips and extraction as your book grows.",
      more: "View all products",
      items: [
        { key: "file", name: "Electric Pedicure File", meta: "12V, 9 speeds, five colors", img: "file-purple.jpg", alt: "Fabeaulous Feet electric pedicure file in purple and white" },
        { key: "remove", name: "REMOVE Discs", meta: "Blue, coarse. Step one.", img: "discs-remove-300.jpg", alt: "Pack of 300 REMOVE disposable dermabrasion discs" },
        { key: "polish", name: "POLISH Discs", meta: "Gray, fine. Step two.", img: "discs-polish-300.jpg", alt: "Pack of 300 POLISH disposable dermabrasion discs" },
        { key: "tip", name: "Stainless Steel Tip", meta: "Medical grade, flat surface", img: "tip-with-discs.jpg", alt: "Fabeaulous Feet stainless steel tip with REMOVE and POLISH discs" },
        { key: "lamp", name: "LED MagniVac Lamp", meta: "Dust vacuum, 30 LEDs, 3x and 8x", img: "magnivac-lamp.jpg", alt: "Fabeaulous LED MagniVac vacuum lamp with magnifier" },
        { key: "mini", name: "Mini E-File", meta: "With Tri-Ball cuticle accessory", img: "mini-e-file.jpg", alt: "Fabeaulous Feet Mini E-File with power adapter" },
      ],
    },
    specs: {
      label: "By the numbers",
      title: "Specs you can check.",
      items: [
        { value: "12", unit: "V", label: "Electric motor with 9 speeds" },
        { value: "1", unit: "set", label: "Of discs per client, single use" },
        { value: "8", unit: "x", label: "Magnifier on the MagniVac Lamp, plus a 3x lens" },
        { value: "12", unit: "mo", label: "Limited warranty on the electric file" },
      ],
    },
    quote: {
      text: "As far as I and my clients are concerned it is the best file system ever. The smoothness lasts far longer than any other and it's half the work.",
      name: "Judy Pentland",
      role: "Good Hair Days",
    },
    reach: {
      label: "Where you'll find us",
      body: "Distributors in Canada, the United States, Portugal and Mexico. Trade show floors from Toronto and Vancouver to Guadalajara and Puebla.",
    },
    paths: {
      label: "Get started",
      title: "Two ways in.",
      salon: { title: "For your salon", body: "Order the complete system, discs and the MagniVac Lamp for your station. We'll send professional pricing and shipping options for your country.", cta: "Request pricing" },
      dist: { title: "Carry the line", body: "Beauty supply stores, schools and distributors: ask about territories and volume pricing in your region.", cta: "Become a distributor" },
    },
    final: {
      title: "Ready for easier service days?",
      body: "Tell us where your salon is and what you need. We reply with pricing and shipping for your country.",
    },
    next: "Next from the workshop: a new disc design, patent pending.",
  },

  products: {
    title: "Products | Fabeaulous Feet Professional Pedicure System",
    description: "Electric pedicure file system, REMOVE and POLISH disposable dermabrasion discs, stainless steel tips, LED MagniVac Lamp, Mini E-File and accessories for professionals.",
    hero: {
      label: "Products",
      title: "The complete pedicure station.",
      sub: "Every product is built for professional use. Ask us for pricing in your country or find your nearest distributor.",
    },
    jump: "Jump to",
    includes: "What's in the box",
    colors: "Colors",
    specs: "Details",
    askPrice: "Request pricing",
    file: {
      id: "electric-file",
      label: "Core tool",
      name: "Electric Pedicure File, Complete System",
      body: "The heart of the system. A light, comfortable grip sized for smaller hands, a 12V motor and a medical grade stainless steel tip. Glide with no pressure and let the speed do the work.",
      specs: ["12V motor with 9 speeds", "Dual LED lights", "3.5 m (11 ft) cord with power adapter", "Eases to low speed under too much pressure", "12-month limited warranty", "Corded model, professional use only"],
      box: ["Electric pedicure file", "Stainless Steel Tip", "Power adapter", "30 REMOVE discs", "30 POLISH discs", "Carry case"],
      colorNames: ["Purple", "Silver", "Black", "Chocolate", "Caramel"],
      imgAlt: "Complete Fabeaulous Feet electric pedicure file system with carry case, adapter and discs",
    },
    discs: {
      id: "discs",
      label: "Consumables",
      name: "Disposable Dermabrasion Discs",
      body: "Self-adhesive discs that peel onto the stainless steel tip. One of each per client, then into the bin. They are too porous to clean, so they are never reused.",
      items: [
        { name: "REMOVE Discs", tag: "Step 1 · Blue · Coarse", body: "For heavy callus, corns, and dry or peeling skin. Use only where needed and avoid sensitive areas.", pack: "Pack of 300", img: "discs-remove-300.jpg", alt: "Pack of 300 REMOVE discs" },
        { name: "POLISH Discs", tag: "Step 2 · Gray · Fine", body: "The finishing step. Smooths the entire surface of the foot. Some feet only need POLISH.", pack: "Pack of 300", img: "discs-polish-300.jpg", alt: "Pack of 300 POLISH discs" },
        { name: "MIXED Package", tag: "Both steps", body: "100 REMOVE and 100 POLISH discs in one bag. A good start for smaller salons.", pack: "Pack of 200", img: "discs-mixed-200.jpg", alt: "MIXED package with 100 REMOVE and 100 POLISH discs" },
      ],
      mx: "In Mexico we also sell packs of 30 REMOVE or 30 POLISH discs.",
    },
    tips: {
      id: "tips",
      label: "Tips",
      name: "Stainless Steel Tips",
      body: "Medical grade stainless steel with a flat, rounded face. It covers more skin than a barrel bit and makes it easy to see how far the reduction has gone.",
      items: [
        { name: "Fabeaulous Feet Stainless Steel Tip", body: "Replacement tip for the Fabeaulous Feet electric file. 3.5 mm shaft. Includes 30 REMOVE and 30 POLISH discs.", img: "stainless-tip.jpg", alt: "Fabeaulous Feet stainless steel tip with engraved logo" },
        { name: "2-Piece Stainless Steel Tip", body: "For rotary files that take a 1/8 in (3.18 mm) shaft. Includes 30 REMOVE and 30 POLISH discs.", img: "tip-discs-flatlay.jpg", alt: "Stainless steel tip laid out with REMOVE and POLISH discs" },
      ],
    },
    lamp: {
      id: "magnivac",
      label: "Dust extraction",
      name: "LED MagniVac Vacuum Lamp",
      body: "Electric filing makes dust. The MagniVac pulls it in at the source while bright LEDs let your client rest in softer room light. Two magnifiers make detail work easy.",
      specs: ["Quiet, powerful dust vacuum", "Washable, easy-change filter (2 included)", "30 bright LED lights", "3x and 8x magnifiers", "Multi-adjustable support arm", "Mounting clamp included"],
      imgAlt: "Technician working under the LED MagniVac Lamp during a pedicure",
      productAlt: "LED MagniVac vacuum lamp product photo",
    },
    detail: {
      id: "detail-tools",
      label: "Detail tools",
      name: "Mini E-File and accessories",
      items: [
        { name: "Mini E-File with Tri-Ball Accessory", body: "Portable and compact with a universal head, so you can use your own bits for acrylic or gel, manicure and pedicure.", img: "mini-e-file.jpg", alt: "Fabeaulous Feet Mini E-File" },
        { name: "Tri-Ball Accessory", body: "Diamond particle balls on 3/32 in (2.38 mm) shafts. Reduce cuticle at the surface without nipping, which helps prevent hangnails.", img: "tri-ball.jpg", alt: "Three Tri-Ball diamond cuticle bits" },
        { name: "Pedi-Cone Accessory", body: "A diamond particle cone on a 3/32 in shaft for dry skin between the toes and other tight spots.", img: "pedi-cone.jpg", alt: "Diamond Pedi-Cone accessory" },
        { name: "Power Adapter", body: "True 12V DC, 4A, with a 3.5 m (11 ft) cord. Replacement for the electric pedicure file.", img: "power-adapter.jpg", alt: "Fabeaulous Feet power adapter" },
      ],
    },
    salon: {
      id: "salon-mexico",
      label: "Available in Mexico",
      name: "Salon essentials",
      body: "Our Mexico catalog adds care products and furniture for the pedicure station.",
      items: [
        { name: "Mint Me foot cream", body: "Moisturizing cream with mint, urea and glycerin. 1 kg, 250 ml and 100 ml.", img: "mint-me-cream.jpg", alt: "Mint Me foot cream jar" },
        { name: "Scrub Me exfoliating gel", body: "Medium grain exfoliant with a fresh mint scent. 1 kg, 250 ml and 100 ml.", img: "scrub-me-gel.jpg", alt: "Scrub Me exfoliating gel jar" },
        { name: "Pedicurist stool", body: "Chrome finish with a footrest that adjusts to 5 heights, so you can work with both hands.", img: "pedicurist-stool.jpg", alt: "Purple pedicurist stool with adjustable footrest" },
        { name: "Client chair", body: "3 adjustable heights and a mount for the MagniVac Lamp.", img: "client-chair.jpg", alt: "Purple client chair for pedicure service" },
      ],
    },
    next: {
      label: "In development",
      title: "Next from the workshop.",
      body: "William is developing a new disc design, patent pending, and a fan for the pedicure station. Ask us to be told first when they're ready.",
      cta: "Get release updates",
    },
  },

  professionals: {
    title: "For Professionals | Why Fabeaulous Feet",
    description: "Why nail techs and pedicurists choose Fabeaulous Feet: gentler work for your hands, a new disc set per client, flat stainless steel tip, easy learning curve, shipping and FAQ.",
    hero: {
      label: "For Professionals",
      title: "Made for the people doing the work.",
      sub: "Fabeaulous Feet was designed by people working in pedicure. Everything from the disc size to the grip was shaped around a long service day.",
    },
    reasons: {
      label: "Why pros switch",
      items: [
        { title: "Easier on your body", body: "Callus reduction is repetitive work. The motor does the reducing, so you can do back-to-back services without the strain that leads to tendinitis, bursitis, epicondylitis and carpal tunnel." },
        { title: "Hygiene you can show", body: "Every client gets a new REMOVE and POLISH disc, opened in front of them. Single use, then discarded." },
        { title: "No blades near the client", body: "No scalpels, no scrapers. The flat stainless steel tip glides over the skin, so there is no edge to cut with." },
        { title: "Results clients feel", body: "The two-step discs leave feet soft and smooth. One client described the service as a relaxing massage." },
      ],
    },
    client: {
      text: "The sensation I feel during the callus reduction service feels like a relaxing massage. The technician works easily, so I just relax and enjoy.",
      who: "Fabeaulous Feet client",
    },
    learn: {
      label: "Learning curve",
      title: "Short training. Steady results.",
      body: "We share basic videos that show the full routine. The rule is simple: no pressure, glide the spinning disc, and let the speed do the work. You were trained on how far callus reduction should go, and the flat tip makes that easy to judge. You stay the guide.",
      imgAlt: "Technician wearing a mask using the electric file and MagniVac Lamp",
    },
    ordering: {
      label: "Ordering",
      title: "How ordering works.",
      items: [
        { title: "Local distributor first", body: "If there is a distributor in your country, we recommend ordering through them. It is usually faster and simpler." },
        { title: "Shipped from Mexico", body: "Direct orders ship from Mexico by courier, such as UPS and DHL. Import duties and taxes are paid by the buyer." },
        { title: "Warranty", body: "The electric file has a 12-month limited warranty. Manufacturing problems are covered for replacement in the first 14 days." },
        { title: "Final sale", body: "All sales are final. We replace product damaged in transit or shipped in error." },
      ],
    },
    faq: {
      label: "FAQ",
      title: "Questions techs ask us.",
      items: [
        { q: "What makes this system different?", a: "It is built for professionals: medical grade stainless steel, a new set of discs for each client, a light and nimble file for smaller hands, and a flat surface that covers more skin than a barrel bit." },
        { q: "What is the difference between the two discs?", a: "The blue REMOVE disc handles heavy callus and difficult skin. The gray POLISH disc is the final step and smooths the whole foot. Some feet only need POLISH." },
        { q: "How often do I change the discs?", a: "After every client. The discs are disposable and too porous to clean, so use one of each per client and discard them." },
        { q: "Why does the file slow down or stop while I work?", a: "You are pressing too hard. The file senses resistance and drops to low speed to protect your client and the motor. Press the top button on the front grip to return to your speed, then glide gently." },
        { q: "Is the electric file cordless?", a: "No. It comes with a 3.5 m (11 ft) power cord." },
        { q: "Does the tip fit other drills?", a: "The Fabeaulous Feet tip is made for our electric file. For other rotary files that take a 1/8 in shaft, use the 2-Piece Stainless Steel Tip." },
        { q: "What is the button on the front of the file?", a: "It is the lock for changing accessories. Never press it while the file is running." },
        { q: "Can you go too far removing callus?", a: "We sell to trained professionals, and you know what can and cannot be done. The flat surface makes it easy to see how far the reduction has gone. Deep cracks heal over time with a good foot cream." },
        { q: "What does the MagniVac Lamp do?", a: "It vacuums the airborne dust from electric filing, lights the foot with bright LEDs and adds 3x and 8x magnifiers for detail work. The filters are washable and easy to change." },
        { q: "Do you sell smaller disc packs?", a: "Yes. The MIXED package has 100 REMOVE and 100 POLISH discs. In Mexico we also sell packs of 30." },
      ],
    },
    dist: {
      label: "Distributors",
      title: "Carry Fabeaulous Feet.",
      body: "We work with beauty supply stores, colleges and distributors in Canada, the United States, Portugal and Mexico. Tell us about your business and your region.",
    },
  },

  about: {
    title: "About | Fabeaulous Feet",
    description: "Fabeaulous Feet was designed in Canada by pedicure professionals and is run today from Nuevo Vallarta, Nayarit, Mexico by William Gordon Johnson and Karina Martinez.",
    hero: {
      label: "About",
      title: "Built by people who do pedicures.",
      sub: "We designed the Fabeaulous Feet system in Canada to stop the cutting and the strain that came with blade work. Today we run it from Nuevo Vallarta, Nayarit.",
    },
    story: {
      label: "Our mission",
      title: "Safe, comfortable, repeatable.",
      p1: "The goal has always been the same: a pedicure system that is easy to use, meets a strict one-client, one-disc hygiene standard, and causes no trauma to the technician or the client.",
      p2: "The answer became a medical grade stainless steel tip and disposable dermabrasion discs, driven by a light electric file. Work gently, and everyone can relax.",
      imgAlt: "Client smiling while a technician works on her feet with the Fabeaulous Feet system",
    },
    people: {
      label: "The team",
      title: "Two people, two sides of the business.",
      items: [
        { initials: "WJ", name: "William Gordon Johnson", role: "Product development", body: "William designs the tools. The tip, the discs and the file grip all come from his bench, and so does the new patent-pending disc." },
        { initials: "KM", name: "Karina Martinez", role: "Business operations", body: "Karina runs the business and her own salon, so the system gets used on real service days. She leads distribution and meets pros at trade shows." },
      ],
    },
    brand: {
      label: "The brand",
      title: "A refreshed identity for 2025.",
      body: "The footprints stayed. The lettering got softer and cleaner, with a deep plum that reads well on packaging, cases and screens.",
    },
    shows: {
      label: "Meet us",
      title: "On the trade show floor.",
      body: "We demo the system in person at professional beauty shows. Recent and regular stops:",
      items: ["ESI Show, Toronto", "Vancouver", "Guadalajara", "Puebla"],
      note: "Want to see it before you buy? Ask where we'll be next.",
    },
  },

  contact: {
    title: "Contact | Request Professional Pricing | Fabeaulous Feet",
    description: "Request professional pricing for the Fabeaulous Feet pedicure system. Message us on WhatsApp, email info@fabeaulousfeet.com or send the form.",
    hero: {
      label: "Contact",
      title: "Let's get your station set up.",
      sub: "Tell us where you work and what you need. We reply with pricing and shipping options for your country, or connect you with your local distributor.",
    },
    channels: {
      waTitle: "WhatsApp",
      waBody: "Fastest way to reach us. English or Spanish.",
      emailTitle: "Email",
      emailBody: "For pricing, orders and distributor questions.",
      baseTitle: "Based in",
      baseBody: "Nuevo Vallarta, Nayarit, Mexico. Shipping worldwide by courier.",
    },
    form: {
      title: "Request pricing",
      intro: "Fields marked * are required.",
      name: "Your name *",
      business: "Salon or business name",
      email: "Email *",
      phone: "Phone or WhatsApp",
      country: "Country *",
      countryOptions: ["Mexico", "Canada", "United States", "Other"],
      role: "I am a *",
      roleOptions: ["Nail tech or pedicurist", "Salon or spa owner", "Beauty school", "Distributor or beauty supply", "Other"],
      interest: "I'm interested in",
      interestOptions: ["Electric file system", "REMOVE / POLISH discs", "Stainless steel tips", "LED MagniVac Lamp", "Distribution"],
      message: "Message",
      messagePh: "Tell us about your salon, volume or questions.",
      submit: "Send request",
      sending: "Sending…",
      success: "Thanks. Your request is in and we'll reply by email soon.",
      error: "Something went wrong. Please email us at info@fabeaulousfeet.com or message us on WhatsApp.",
      subject: "New pricing request from fabeaulousfeet website (EN)",
      privacy: "We only use your details to answer this request.",
    },
    dist: {
      title: "Distributor countries",
      body: "Canada, United States, Portugal and Mexico. If there is a distributor near you, we'll point you to them.",
    },
  },

  notFound: {
    title: "Page not found | Fabeaulous Feet",
    heading: "This page walked off.",
    body: "The link may be old or mistyped. Try one of these instead.",
  },
};

const es = {
  langName: "Español",
  otherLangLabel: "English",
  skip: "Ir al contenido",
  nav: {
    products: "Productos",
    professionals: "Para profesionales",
    about: "Nosotros",
    contact: "Contacto",
    cta: "Solicitar precios",
    menu: "Menú",
    close: "Cerrar",
    home: "Inicio de Fabeaulous Feet",
  },
  cta: {
    pricing: "Solicitar precios",
    whatsapp: "Escríbenos por WhatsApp",
    email: "Envíanos un correo",
    system: "Conoce el sistema",
    distributor: "Quiero ser distribuidor",
    waText: "Hola Fabeaulous Feet, me gustaría recibir precios profesionales del sistema de pedicure.",
  },
  footer: {
    blurb: "Un sistema profesional de pedicure diseñado por gente que hace pedicure. Lima, punta de acero y discos nuevos para cada cliente.",
    explore: "Explora",
    talk: "Hablemos",
    follow: "Síguenos",
    pros: "De uso profesional. A la venta para profesionales capacitados en uñas y cuidado del pie.",
    rights: "Todos los derechos reservados.",
    langSwitch: "View in English",
  },

  home: {
    title: "Fabeaulous Feet | Sistema Profesional de Pedicure",
    description: "Lima eléctrica para pedicure, punta de acero inoxidable grado médico y discos desechables REMOVER y PULIR. Para profesionales del cuidado del pie en México, Canadá y EE. UU.",
    hero: {
      label: "Sistema Profesional de Pedicure",
      line1: "Pies suaves.",
      line2: "Manos tranquilas.",
      sub: "Una lima eléctrica, una punta de acero inoxidable y discos nuevos para cada cliente. Creado por profesionales del pedicure, para profesionales del pedicure.",
      imgAlt: "Pedicurista usando la lima eléctrica Fabeaulous Feet en el pie de una clienta, bajo la lámpara LED MagniVac",
      note: "Diseñado en Canadá. Enviado desde México.",
    },
    manifesto: {
      label: "Por qué existe",
      small: "Las navajas y los raspadores siguen haciendo casi todo el trabajo de callosidades.",
      big: "La navaja corta al cliente. El mismo movimiento, temporada tras temporada, te lastima las muñecas. Creamos un sistema que hace el trabajo para cuidar tus manos.",
      injuries: "Tendinitis. Bursitis. Epicondilitis. Túnel carpiano.",
      injuriesNote: "Las lesiones por movimiento repetitivo que este sistema busca evitar.",
    },
    steps: {
      label: "Cómo funciona",
      title: "Dos discos. Un deslizamiento suave.",
      intro: "Toda la reducción de callosidades cabe en cuatro pasos. Sin presión. Deja que la velocidad haga el trabajo.",
      items: [
        { n: "01", title: "Coloca un disco nuevo", body: "Los discos autoadheribles se pegan directo en la punta de acero inoxidable. Un juego nuevo por cliente, así no hay nada que esterilizar entre servicios." },
        { n: "02", title: "REMOVER las durezas", body: "El disco azul REMOVER se encarga de callosidades gruesas, callos y piel seca o escamosa. Úsalo solo donde se necesita y evita las zonas sensibles." },
        { n: "03", title: "PULIR todo el pie", body: "El disco gris PULIR deja suave toda la superficie del pie. Algunos clientes solo necesitan este paso." },
        { n: "04", title: "Retira. Desecha. Listo.", body: "Los dos discos van a la basura. Tu cliente se va con los pies suaves y tú sigues con el siguiente servicio sin cansar las manos." },
      ],
    },
    tip: {
      label: "La punta",
      title: "Plana donde otras son redondas.",
      body: "La mayoría de las fresas tienen forma de barril y tocan una franja muy delgada de piel, lo que facilita que se caliente y queme. Nuestra punta de acero inoxidable grado médico es plana y redondeada: cubre más superficie y te deja ver con claridad cuánto has avanzado.",
      points: [
        "Del tamaño justo para trabajar alrededor y entre los dedos",
        "La lima baja a velocidad lenta si presionas de más",
        "Tú decides cuánto retirar",
      ],
      imgAlt: "Acercamiento de la lima eléctrica Fabeaulous Feet con disco en la punta de acero, trabajando en el talón",
    },
    system: {
      label: "El sistema",
      title: "Todo lo que tu estación necesita.",
      intro: "Empieza con el kit completo de lima eléctrica y suma discos, puntas y extracción de polvo conforme crece tu agenda.",
      more: "Ver todos los productos",
      items: [
        { key: "file", name: "Lima eléctrica para pedicure", meta: "12V, 9 velocidades, cinco colores", img: "file-purple.jpg", alt: "Lima eléctrica Fabeaulous Feet en morado y blanco" },
        { key: "remove", name: "Discos REMOVER", meta: "Azul, grueso. Paso uno.", img: "discs-remove-300.jpg", alt: "Paquete con 300 discos dermoabrasivos REMOVER" },
        { key: "polish", name: "Discos PULIR", meta: "Gris, fino. Paso dos.", img: "discs-polish-300.jpg", alt: "Paquete con 300 discos dermoabrasivos PULIR" },
        { key: "tip", name: "Punta de acero inoxidable", meta: "Grado médico, superficie plana", img: "tip-with-discs.jpg", alt: "Punta de acero inoxidable Fabeaulous Feet con discos REMOVER y PULIR" },
        { key: "lamp", name: "Lámpara LED MagniVac", meta: "Extractor de polvo, 30 LED, lupas 3x y 8x", img: "magnivac-lamp.jpg", alt: "Lámpara con extractor LED MagniVac y lupa" },
        { key: "mini", name: "Mini E-File", meta: "Con puntas Tri-Ball para cutícula", img: "mini-e-file.jpg", alt: "Mini E-File de Fabeaulous Feet" },
      ],
    },
    specs: {
      label: "En números",
      title: "Datos que puedes comprobar.",
      items: [
        { value: "12", unit: "V", label: "Motor eléctrico con 9 velocidades" },
        { value: "1", unit: "juego", label: "De discos por cliente, de un solo uso" },
        { value: "8", unit: "x", label: "Lupa de la lámpara MagniVac, además de una de 3x" },
        { value: "12", unit: "meses", label: "De garantía limitada en la lima eléctrica" },
      ],
    },
    quote: {
      text: "Para mí y para mis clientes es el mejor sistema de lima que existe. La suavidad dura mucho más que con cualquier otro y es la mitad del trabajo.",
      name: "Judy Pentland",
      role: "Good Hair Days (traducción del inglés)",
    },
    reach: {
      label: "Dónde encontrarnos",
      body: "Distribuidores en Canadá, Estados Unidos, Portugal y México. Y en expos profesionales de Toronto y Vancouver a Guadalajara y Puebla.",
    },
    paths: {
      label: "Empieza hoy",
      title: "Dos caminos.",
      salon: { title: "Para tu salón", body: "Pide el kit completo, discos y la lámpara MagniVac para tu estación. Te enviamos precios profesionales y opciones de envío para tu país.", cta: "Solicitar precios" },
      dist: { title: "Distribuye la marca", body: "Tiendas de belleza, escuelas y distribuidores: pregúntanos por zonas disponibles y precios por volumen en tu región.", cta: "Quiero ser distribuidor" },
    },
    final: {
      title: "¿Todo listo para días de servicio más ligeros?",
      body: "Cuéntanos dónde está tu salón y qué necesitas. Te respondemos con precios y envío a tu país.",
    },
    next: "Lo próximo del taller: un nuevo diseño de disco, con patente en trámite.",
  },

  products: {
    title: "Productos | Fabeaulous Feet Sistema Profesional de Pedicure",
    description: "Kit de lima eléctrica para pedicure, discos dermoabrasivos desechables REMOVER y PULIR, puntas de acero inoxidable, lámpara LED MagniVac, Mini E-File y accesorios profesionales.",
    hero: {
      label: "Productos",
      title: "Tu estación de pedicure, completa.",
      sub: "Todos los productos son de uso profesional. Pídenos precios para tu país o te conectamos con tu distribuidor más cercano.",
    },
    jump: "Ir a",
    includes: "Qué incluye",
    colors: "Colores",
    specs: "Detalles",
    askPrice: "Solicitar precios",
    file: {
      id: "lima-electrica",
      label: "Herramienta principal",
      name: "Kit de lima eléctrica para pedicure",
      body: "El corazón del sistema. Ligera, cómoda y pensada para manos pequeñas, con motor de 12V y punta de acero inoxidable grado médico. Desliza sin presión y deja que la velocidad trabaje.",
      specs: ["Motor de 12V con 9 velocidades", "Doble luz LED", "Cable de 3.5 m con adaptador de corriente", "Baja a velocidad lenta si hay demasiada presión", "Garantía limitada de 12 meses", "Modelo con cable, de uso profesional"],
      box: ["Lima eléctrica para pedicure", "Punta de acero inoxidable", "Adaptador de corriente", "30 discos REMOVER", "30 discos PULIR", "Estuche"],
      colorNames: ["Morado", "Plata", "Negro", "Chocolate", "Caramelo"],
      imgAlt: "Kit completo de lima eléctrica Fabeaulous Feet con estuche, adaptador y discos",
    },
    discs: {
      id: "discos",
      label: "Consumibles",
      name: "Discos dermoabrasivos desechables",
      body: "Discos autoadheribles que se pegan en la punta de acero. Uno de cada uno por cliente y a la basura. Son demasiado porosos para limpiarse, así que nunca se reutilizan.",
      items: [
        { name: "Discos REMOVER", tag: "Paso 1 · Azul · Grueso", body: "Para callosidades duras, callos y piel seca o escamosa. Úsalo solo donde se necesita y evita zonas sensibles.", pack: "Paquete de 300", img: "discs-remove-300.jpg", alt: "Paquete de 300 discos REMOVER" },
        { name: "Discos PULIR", tag: "Paso 2 · Gris · Fino", body: "El toque final. Deja suave toda la superficie del pie. Algunos pies solo necesitan PULIR.", pack: "Paquete de 300", img: "discs-polish-300.jpg", alt: "Paquete de 300 discos PULIR" },
        { name: "Paquete mixto", tag: "Los dos pasos", body: "100 discos REMOVER y 100 discos PULIR en una sola bolsa. Ideal para empezar en salones pequeños.", pack: "Paquete de 200", img: "discs-mixed-200.jpg", alt: "Paquete mixto con 100 discos REMOVER y 100 PULIR" },
      ],
      mx: "En México también manejamos paquetes de 30 discos REMOVER o 30 discos PULIR.",
    },
    tips: {
      id: "puntas",
      label: "Puntas",
      name: "Puntas de acero inoxidable",
      body: "Acero inoxidable grado médico con cara plana y redondeada. Cubre más piel que una fresa de barril y te deja ver cuánto has reducido.",
      items: [
        { name: "Punta de acero inoxidable Fabeaulous Feet", body: "Repuesto para la lima eléctrica Fabeaulous Feet. Eje de 3.5 mm. Incluye 30 discos REMOVER y 30 PULIR.", img: "stainless-tip.jpg", alt: "Punta de acero inoxidable Fabeaulous Feet con logo grabado" },
        { name: "Punta de acero inoxidable de 2 piezas", body: "Para limas rotativas con boquilla de 1/8 in (3.18 mm). Incluye 30 discos REMOVER y 30 PULIR.", img: "tip-discs-flatlay.jpg", alt: "Punta de acero inoxidable con discos REMOVER y PULIR" },
      ],
    },
    lamp: {
      id: "magnivac",
      label: "Extracción de polvo",
      name: "Lámpara con extractor LED MagniVac",
      body: "Limar genera polvo. La MagniVac lo atrapa desde el origen, y sus luces LED te dejan ver bien mientras tu cliente descansa con luz tenue. Dos lupas facilitan el trabajo de detalle.",
      specs: ["Extractor de polvo potente y silencioso", "Filtro lavable y fácil de cambiar (incluye 2)", "30 luces LED brillantes", "Lupas de 3x y 8x", "Brazo de soporte multiajustable", "Pinza de sujeción incluida"],
      imgAlt: "Pedicurista trabajando bajo la lámpara LED MagniVac",
      productAlt: "Foto de producto de la lámpara con extractor LED MagniVac",
    },
    detail: {
      id: "detalle",
      label: "Herramientas de detalle",
      name: "Mini E-File y accesorios",
      items: [
        { name: "Mini E-File con puntas Tri-Ball", body: "Portátil y compacta, con cabezal universal para usar tus fresas favoritas en uñas acrílicas o de gel, manos y pies.", img: "mini-e-file.jpg", alt: "Mini E-File de Fabeaulous Feet" },
        { name: "Puntas Tri-Ball", body: "Esferas con polvo de diamante en ejes de 3/32 in (2.38 mm). Reducen la cutícula sin cortar y ayudan a prevenir padrastros.", img: "tri-ball.jpg", alt: "Tres puntas Tri-Ball de diamante" },
        { name: "Accesorio Pedi-Cone", body: "Cono con polvo de diamante en eje de 3/32 in para retirar piel seca entre los dedos y en zonas difíciles.", img: "pedi-cone.jpg", alt: "Accesorio Pedi-Cone de diamante" },
        { name: "Adaptador de corriente", body: "12V DC reales, 4A, con cable de 3.5 m. Repuesto para la lima eléctrica.", img: "power-adapter.jpg", alt: "Adaptador de corriente Fabeaulous Feet" },
      ],
    },
    salon: {
      id: "salon-mexico",
      label: "Disponible en México",
      name: "Esenciales para tu salón",
      body: "Nuestro catálogo en México suma productos de cuidado y mobiliario para la estación de pedicure.",
      items: [
        { name: "Crema humectante Mint Me", body: "Con menta, urea y glicerina. Deja el pie con sensación fresca. 1 kg, 250 ml y 100 ml.", img: "mint-me-cream.jpg", alt: "Frasco de crema Mint Me" },
        { name: "Gel exfoliante Scrub Me", body: "Exfoliante de grano medio con rico aroma a menta. 1 kg, 250 ml y 100 ml.", img: "scrub-me-gel.jpg", alt: "Frasco de gel exfoliante Scrub Me" },
        { name: "Banco para pedicurista", body: "Acabado en cromo, con recarga-pie de 5 alturas para trabajar libremente con las dos manos.", img: "pedicurist-stool.jpg", alt: "Banco morado para pedicurista con recarga-pie ajustable" },
        { name: "Silla para clientes", body: "3 alturas ajustables y soporte para la lámpara MagniVac.", img: "client-chair.jpg", alt: "Silla morada para clientes de pedicure" },
      ],
    },
    next: {
      label: "En desarrollo",
      title: "Lo próximo del taller.",
      body: "William está desarrollando un nuevo diseño de disco, con patente en trámite, y un ventilador para la estación de pedicure. Pídenos que te avisemos primero.",
      cta: "Quiero enterarme",
    },
  },

  professionals: {
    title: "Para profesionales | Por qué Fabeaulous Feet",
    description: "Por qué pedicuristas y técnicas en uñas eligen Fabeaulous Feet: menos desgaste en tus manos, discos nuevos por cliente, punta plana de acero, aprendizaje rápido, envíos y preguntas frecuentes.",
    hero: {
      label: "Para profesionales",
      title: "Hecho para quien hace el trabajo.",
      sub: "Fabeaulous Feet lo diseñó gente que trabaja en pedicure. Desde el tamaño del disco hasta el agarre de la lima, todo se pensó para un día largo de servicios.",
    },
    reasons: {
      label: "Por qué se cambian",
      items: [
        { title: "Menos desgaste para tu cuerpo", body: "Reducir callosidades es trabajo repetitivo. El motor hace la reducción, así puedes hacer servicio tras servicio sin la tensión que lleva a tendinitis, bursitis, epicondilitis y túnel carpiano." },
        { title: "Higiene que se ve", body: "Cada cliente recibe un disco REMOVER y uno PULIR nuevos, abiertos frente a tu cliente. De un solo uso y a la basura." },
        { title: "Sin navajas cerca del cliente", body: "Ni bisturí ni raspador. La punta plana de acero se desliza sobre la piel: no tiene filo que corte." },
        { title: "Resultados que se sienten", body: "Los discos de dos pasos dejan los pies suaves y tersos. Un cliente lo describió como un masaje relajante." },
      ],
    },
    client: {
      text: "Durante la reducción de callosidades la sensación es como un masaje relajante. La técnica trabaja con facilidad, así que yo solo me relajo y disfruto.",
      who: "Cliente de Fabeaulous Feet",
    },
    learn: {
      label: "Aprendizaje",
      title: "Capacitación corta. Resultados constantes.",
      body: "Compartimos videos básicos con todo el procedimiento. La regla es sencilla: sin presión, desliza el disco girando y deja que la velocidad trabaje. Tú aprendiste hasta dónde llega una reducción de callosidades, y la punta plana te ayuda a medirlo. Tú marcas el ritmo.",
      imgAlt: "Pedicurista con cubrebocas usando la lima eléctrica y la lámpara MagniVac",
    },
    ordering: {
      label: "Pedidos",
      title: "Cómo funcionan los pedidos.",
      items: [
        { title: "Primero tu distribuidor", body: "Si hay un distribuidor en tu país, te recomendamos comprar con él. Normalmente es más rápido y sencillo." },
        { title: "Envíos desde México", body: "Los pedidos directos salen de México por paquetería, como UPS y DHL. Los impuestos y aranceles de importación corren por cuenta del comprador." },
        { title: "Garantía", body: "La lima eléctrica tiene garantía limitada de 12 meses. Los defectos de fabricación se reemplazan durante los primeros 14 días." },
        { title: "Venta final", body: "Todas las ventas son finales. Reponemos producto dañado en el envío o enviado por error." },
      ],
    },
    faq: {
      label: "Preguntas frecuentes",
      title: "Lo que más nos preguntan.",
      items: [
        { q: "¿Qué hace diferente a este sistema?", a: "Está hecho para profesionales: acero inoxidable grado médico, discos nuevos para cada cliente, una lima ligera y ágil para manos pequeñas, y una superficie plana que cubre más piel que una fresa de barril." },
        { q: "¿Cuál es la diferencia entre los dos discos?", a: "El disco azul REMOVER trabaja callosidades gruesas y piel difícil. El disco gris PULIR es el paso final y deja suave todo el pie. Algunos pies solo necesitan PULIR." },
        { q: "¿Cada cuándo cambio los discos?", a: "Después de cada cliente. Son desechables y demasiado porosos para limpiarse, así que usa uno de cada uno por cliente y deséchalos." },
        { q: "¿Por qué la lima baja de velocidad o se detiene mientras trabajo?", a: "Estás presionando de más. La lima detecta la resistencia y baja a velocidad lenta para proteger a tu cliente y al motor. Presiona el botón superior del agarre frontal para volver a tu velocidad y desliza con suavidad." },
        { q: "¿La lima eléctrica es inalámbrica?", a: "No. Incluye un cable de corriente de 3.5 m." },
        { q: "¿La punta le queda a otros tornos?", a: "La punta Fabeaulous Feet está hecha para nuestra lima. Para otras limas rotativas con boquilla de 1/8 in, usa la punta de acero inoxidable de 2 piezas." },
        { q: "¿Para qué es el botón del frente de la lima?", a: "Es el seguro para cambiar accesorios. Nunca lo presiones con la lima encendida." },
        { q: "¿Se puede retirar demasiada callosidad?", a: "Vendemos a profesionales capacitados y tú sabes lo que se puede y no se puede hacer. La superficie plana facilita ver cuánto has reducido. Las grietas profundas sanan con el tiempo y una buena crema para pies." },
        { q: "¿Qué hace la lámpara MagniVac?", a: "Aspira el polvo que genera el limado eléctrico, ilumina el pie con luces LED y suma lupas de 3x y 8x para el detalle. Los filtros son lavables y fáciles de cambiar." },
        { q: "¿Venden paquetes de discos más chicos?", a: "Sí. El paquete mixto trae 100 discos REMOVER y 100 PULIR. En México también manejamos paquetes de 30." },
      ],
    },
    dist: {
      label: "Distribuidores",
      title: "Distribuye Fabeaulous Feet.",
      body: "Trabajamos con tiendas de belleza, escuelas y distribuidores en Canadá, Estados Unidos, Portugal y México. Cuéntanos de tu negocio y tu región.",
    },
  },

  about: {
    title: "Nosotros | Fabeaulous Feet",
    description: "Fabeaulous Feet se diseñó en Canadá por profesionales del pedicure y hoy opera desde Nuevo Vallarta, Nayarit, con William Gordon Johnson y Karina Martinez.",
    hero: {
      label: "Nosotros",
      title: "Hecho por gente que hace pedicure.",
      sub: "Diseñamos el sistema Fabeaulous Feet en Canadá para acabar con las cortadas y el desgaste que traía el trabajo con navaja. Hoy lo operamos desde Nuevo Vallarta, Nayarit.",
    },
    story: {
      label: "Nuestra misión",
      title: "Seguro, cómodo y constante.",
      p1: "La meta siempre ha sido la misma: un sistema de pedicure fácil de usar, con una regla estricta de higiene de un disco por cliente, y sin lastimar ni a la pedicurista ni al cliente.",
      p2: "La respuesta fue una punta de acero inoxidable grado médico y discos dermoabrasivos desechables, movidos por una lima eléctrica ligera. Se trabaja con suavidad y todos se relajan.",
      imgAlt: "Clienta sonriendo mientras la pedicurista trabaja en sus pies con el sistema Fabeaulous Feet",
    },
    people: {
      label: "El equipo",
      title: "Dos personas, dos lados del negocio.",
      items: [
        { initials: "WJ", name: "William Gordon Johnson", role: "Desarrollo de producto", body: "William diseña las herramientas. La punta, los discos y el agarre de la lima salen de su mesa de trabajo, igual que el nuevo disco con patente en trámite." },
        { initials: "KM", name: "Karina Martinez", role: "Operación del negocio", body: "Karina dirige el negocio y su propio salón, así que el sistema se usa en días reales de servicio. Ella lleva la distribución y atiende a los profesionales en las expos." },
      ],
    },
    brand: {
      label: "La marca",
      title: "Una identidad renovada en 2025.",
      body: "Las huellas se quedaron. Las letras se volvieron más suaves y limpias, con un ciruela profundo que luce bien en empaques, estuches y pantallas.",
    },
    shows: {
      label: "Conócenos",
      title: "En el piso de la expo.",
      body: "Hacemos demostraciones en vivo en expos profesionales de belleza. Paradas recientes y frecuentes:",
      items: ["ESI Show, Toronto", "Vancouver", "Guadalajara", "Puebla"],
      note: "¿Quieres verlo antes de comprar? Pregúntanos dónde estaremos.",
    },
  },

  contact: {
    title: "Contacto | Solicita precios profesionales | Fabeaulous Feet",
    description: "Solicita precios profesionales del sistema de pedicure Fabeaulous Feet. Escríbenos por WhatsApp, a info@fabeaulousfeet.com o envía el formulario.",
    hero: {
      label: "Contacto",
      title: "Armemos tu estación.",
      sub: "Cuéntanos dónde trabajas y qué necesitas. Te respondemos con precios y opciones de envío para tu país, o te conectamos con tu distribuidor.",
    },
    channels: {
      waTitle: "WhatsApp",
      waBody: "La forma más rápida de contactarnos. En español o inglés.",
      emailTitle: "Correo",
      emailBody: "Para precios, pedidos y distribución.",
      baseTitle: "Estamos en",
      baseBody: "Nuevo Vallarta, Nayarit, México. Envíos a todo el mundo por paquetería.",
    },
    form: {
      title: "Solicitar precios",
      intro: "Los campos con * son obligatorios.",
      name: "Tu nombre *",
      business: "Nombre del salón o negocio",
      email: "Correo electrónico *",
      phone: "Teléfono o WhatsApp",
      country: "País *",
      countryOptions: ["México", "Canadá", "Estados Unidos", "Otro"],
      role: "Soy *",
      roleOptions: ["Pedicurista o manicurista", "Dueña o dueño de salón o spa", "Escuela de belleza", "Distribuidor o tienda de belleza", "Otro"],
      interest: "Me interesa",
      interestOptions: ["Kit de lima eléctrica", "Discos REMOVER / PULIR", "Puntas de acero inoxidable", "Lámpara LED MagniVac", "Distribución"],
      message: "Mensaje",
      messagePh: "Cuéntanos de tu salón, volumen o dudas.",
      submit: "Enviar solicitud",
      sending: "Enviando…",
      success: "Gracias. Recibimos tu solicitud y te responderemos pronto por correo.",
      error: "Algo salió mal. Escríbenos a info@fabeaulousfeet.com o por WhatsApp.",
      subject: "Nueva solicitud de precios desde el sitio fabeaulousfeet (ES)",
      privacy: "Solo usamos tus datos para responder esta solicitud.",
    },
    dist: {
      title: "Países con distribuidor",
      body: "Canadá, Estados Unidos, Portugal y México. Si hay un distribuidor cerca de ti, te ponemos en contacto.",
    },
  },

  notFound: {
    title: "Página no encontrada | Fabeaulous Feet",
    heading: "Esta página se fue caminando.",
    body: "El enlace puede ser antiguo o tener un error. Prueba con alguna de estas opciones.",
  },
};

export default { en, es };
